local LootDistr, LDData = ...
local localeBasedMessages = {}

-- English (enUS)
localeBasedMessages["enUS"] = {
  system = {
    addonLoaded = "Addon Loaded",
    moduleEnabled = "Loot roll module enabled.",
    moduleDisabled = "Loot roll module disabled.",
    joinedRaid = "Loot Watcher activated, parsing threshold:",
    leftRaid = "Loot Watcher deactivated.",
    trackedLoot = "Tracked loot:",
    lootRollingEnded = "Loot Rolling ended.",
    reRollConfirmed = "Re-roll confirmed.",
    noEligibleReRolls = "No eligible re-rolls.",
    noItemRolling = "No item is currently being rolled.",
    softResImported = "Imported soft reserves!",
    softResOverwrite = "Soft reserve data already exists. Importing new data will overwrite it. Continue?",
    csvParseError = "CSV parse error:",
    lootWatcherDataDeleted = "All loot watcher data has been deleted.",
    rollStartWithReserves = "Roll for: %s - Reserved by: %s",
    rollStartNoReserves = "Roll for: %s - No soft reserves. /roll - MS, /roll 99 - OS",
    rollAnnounceLocalization = "Current roll announcement locale: %s",
    rollEndsSoon = "Rolling ends in %s",
    rollEndedWinner = "Rolling ended. Winner: %s with roll - %d (%s spec)",
    rollEndedNoRolls = "Rolling ended. No rolls recorded.",
    itemIDError = "Could not get itemID or link.",
    notLootMaster = "You are not the loot master.",
    notInRaid = "You are not in the raid group.",
    lootNotMaster = "Master loot is not enabled. Current loot system: %s",
    noCSVText = "No CSV text to import!",
    invalidCSVFormat = "Not a valid CSV format (missing commas or header row).",
    missingCSVColumn = "CSV is missing required column: |cffffff00%s|r",
    softResDeleted = "All soft reserves have been deleted.",
    thresholdChanged = "Loot Watcher parsing threshold changed to: %s",
    itemIsBeingRolledFor = "Rolling session for %s has not ended yet.",
    rollingCancelled = "Rolling session for %s was cancelled.",
  },
  dialogs = {
    confirmEndRoll = "Are you sure you want to end rolling?",
    confirmReRoll = "Are you sure you want to re-roll this item?",
    confirmCancelRoll = "Are you sure you want to cancel roll session?",
    confirmOverwrite = "Soft reserve data already exists. Importing new data will overwrite it. Continue?",
    confirmDeleteWatcher = "Are you sure you want to delete ALL loot watcher data? This cannot be undone.",
    confirmDeleteSoftRes = "Are you sure you want to delete ALL soft reserves data? This cannot be undone.",
    yes = "Yes",
    no = "No",
  },
  regex = {
    playerLoot = "^(.+) receives loot: (.+)%.$",
    selfLoot = "^You receive loot: (.+)%.$",
    goldShare = "Your share of the loot is",
    gold = "(%d+)%s*Gold",
    silver = "(%d+)%s*Silver",
    copper = "(%d+)%s*Copper",
    systemRoll = "^(%S+) rolls (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Search reserves...",
    searchLoot = "Search loot...",
  },
}

-- German (deDE)
localeBasedMessages["deDE"] = {
  system = {
    addonLoaded = "Addon geladen",
    moduleEnabled = "Loot-Roll-Modul aktiviert.",
    moduleDisabled = "Loot-Roll-Modul deaktiviert.",
    joinedRaid = "Du bist der Schlachtzuggruppe beigetreten. Loot-Watcher aktiviert, Parse-Schwelle:",
    leftRaid = "Du hast die Schlachtzuggruppe verlassen. Loot-Watcher deaktiviert.",
    trackedLoot = "Verfolgtes Loot:",
    lootRollingEnded = "Loot-Rolling beendet.",
    reRollConfirmed = "Neuer Wurf bestätigt.",
    noEligibleReRolls = "Keine berechtigten Neuwürfe.",
    noItemRolling = "Derzeit wird für kein Item gewürfelt.",
    softResImported = "Soft-Reserve importiert!",
    softResOverwrite = "Soft-Reserve-Daten existieren bereits. Das Importieren neuer Daten wird sie überschreiben. Fortfahren?",
    csvParseError = "CSV-Parse-Fehler:",
    lootWatcherDataDeleted = "Alle Loot-Watcher-Daten wurden gelöscht.",
    rollStartWithReserves = "Würfle für: %s - Reserviert von: %s",
    rollStartNoReserves = "Würfle für: %s - Keine Soft-Reserve. /roll - MS, /roll 99 - OS",
    rollAnnounceLocalization = "Aktuelle Wurf-Ankündigungssprache: %s",
    rollEndsSoon = "Würfeln endet in %s",
    rollEndedWinner = "Würfeln beendet. Gewinner: %s mit Wurf - %d (%s Spezialisierung)",
    rollEndedNoRolls = "Würfeln beendet. Keine Würfe aufgezeichnet.",
    itemIDError = "Konnte ItemID oder Link nicht abrufen.",
    notLootMaster = "Du bist nicht der Loot-Master.",
    notInRaid = "Du bist nicht in der Schlachtzuggruppe.",
    lootNotMaster = "Master-Loot ist nicht aktiviert. Aktuelles Loot-System: %s",
    noCSVText = "Kein CSV-Text zum Importieren!",
    invalidCSVFormat = "Kein gültiges CSV-Format (fehlende Kommas oder Kopfzeile).",
    missingCSVColumn = "CSV fehlt erforderliche Spalte: |cffffff00%s|r",
    softResDeleted = "Alle Soft-Reserve wurden gelöscht.",
    thresholdChanged = "Loot-Watcher-Parse-Schwelle geändert auf: %s",
    itemIsBeingRolledFor = "Würfel-Session für %s ist noch nicht beendet.",
    rollingCancelled = "Würfel-Session für %s wurde abgebrochen.",
  },
  dialogs = {
    confirmEndRoll = "Bist du sicher, dass du das Würfeln beenden möchtest?",
    confirmReRoll = "Bist du sicher, dass du für dieses Item neu würfeln möchtest?",
    confirmCancelRoll = "Bist du sicher, dass du die Würfel-Session abbrechen möchtest?",
    confirmOverwrite = "Soft-Reserve-Daten existieren bereits. Das Importieren neuer Daten wird sie überschreiben. Fortfahren?",
    confirmDeleteWatcher = "Bist du sicher, dass du ALLE Loot-Watcher-Daten löschen möchtest? Dies kann nicht rückgängig gemacht werden.",
    confirmDeleteSoftRes = "Bist du sicher, dass du ALLE Soft-Reserve-Daten löschen möchtest? Dies kann nicht rückgängig gemacht werden.",
    yes = "Ja",
    no = "Nein",
  },
  regex = {
    playerLoot = "^(.+) erhält Beute: (.+)%.$",
    selfLoot = "^Du erhältst Beute: (.+)%.$",
    goldShare = "Dein Anteil an der Beute beträgt",
    gold = "(%d+)%s*Gold",
    silver = "(%d+)%s*Silber",
    copper = "(%d+)%s*Kupfer",
    systemRoll = "^(%S+) würfelt (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Reservierungen suchen...",
    searchLoot = "Loot suchen...",
  },
}

-- French (frFR)
localeBasedMessages["frFR"] = {
  system = {
    addonLoaded = "Extension chargée",
    moduleEnabled = "Module de loot roll activé.",
    moduleDisabled = "Module de loot roll désactivé.",
    joinedRaid = "Vous avez rejoint le groupe de raid. Surveillant de butin activé, seuil d'analyse:",
    leftRaid = "Vous avez quitté le groupe de raid. Surveillant de butin désactivé.",
    trackedLoot = "Butin suivi:",
    lootRollingEnded = "Loot Rolling terminé.",
    reRollConfirmed = "Nouveau jet confirmé.",
    noEligibleReRolls = "Aucun nouveau jet éligible.",
    noItemRolling = "Aucun objet n'est actuellement en cours de jet.",
    softResImported = "Soft-Reserve importées!",
    softResOverwrite = "Les données de soft-reserve existent déjà. L'importation de nouvelles données les écrasera. Continuer?",
    csvParseError = "Erreur d'analyse CSV:",
    lootWatcherDataDeleted = "Toutes les données du surveillant de butin ont été supprimées.",
    rollStartWithReserves = "Jet pour: %s - Réservé par: %s",
    rollStartNoReserves = "Jet pour: %s - Aucune soft-reserve. /roll - MS, /roll 99 - OS",
    rollAnnounceLocalization = "Langue d'annonce de jet actuelle: %s",
    rollEndsSoon = "Le jet se termine dans %s",
    rollEndedWinner = "Jet terminé. Gagnant: %s avec jet - %d (spéc %s)",
    rollEndedNoRolls = "Jet terminé. Aucun jet enregistré.",
    itemIDError = "Impossible d'obtenir l'ID d'objet ou le lien.",
    notLootMaster = "Vous n'êtes pas le maître du butin.",
    notInRaid = "Vous n'êtes pas dans le groupe de raid.",
    lootNotMaster = "Le butin maître n'est pas activé. Système de butin actuel: %s",
    noCSVText = "Aucun texte CSV à importer!",
    invalidCSVFormat = "Format CSV non valide (virgules manquantes ou ligne d'en-tête).",
    missingCSVColumn = "CSV manque la colonne requise: |cffffff00%s|r",
    softResDeleted = "Toutes les soft-reserve ont été supprimées.",
    thresholdChanged = "Seuil d'analyse du surveillant de butin changé à: %s",
    itemIsBeingRolledFor = "La session de jet pour %s n'est pas encore terminée.",
    rollingCancelled = "La session de jet pour %s a été annulée.",
  },
  dialogs = {
    confirmEndRoll = "Êtes-vous sûr de vouloir terminer le jet?",
    confirmReRoll = "Êtes-vous sûr de vouloir relancer pour cet objet?",
    confirmCancelRoll = "Êtes-vous sûr de vouloir annuler la session de jet?",
    confirmOverwrite = "Les données de soft-reserve existent déjà. L'importation de nouvelles données les écrasera. Continuer?",
    confirmDeleteWatcher = "Êtes-vous sûr de vouloir supprimer TOUTES les données du surveillant de butin? Cela ne peut pas être annulé.",
    confirmDeleteSoftRes = "Êtes-vous sûr de vouloir supprimer TOUTES les données de soft-reserve? Cela ne peut pas être annulé.",
    yes = "Oui",
    no = "Non",
  },
  regex = {
    playerLoot = "^(.+) reçoit le butin : (.+)%.$",
    selfLoot = "^Vous recevez le butin : (.+)%.$",
    goldShare = "Votre part du butin est",
    gold = "(%d+)%s*Or",
    silver = "(%d+)%s*Argent",
    copper = "(%d+)%s*Cuivre",
    systemRoll = "^(%S+) fait (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Rechercher réserves...",
    searchLoot = "Rechercher butin...",
  },
}

-- Spanish (esES)
localeBasedMessages["esES"] = {
  system = {
    addonLoaded = "Addon cargado",
    moduleEnabled = "Módulo de loot roll activado.",
    moduleDisabled = "Módulo de loot roll desactivado.",
    joinedRaid = "Te has unido al grupo de banda. Vigilante de botín activado, umbral de análisis:",
    leftRaid = "Has abandonado el grupo de banda. Vigilante de botín desactivado.",
    trackedLoot = "Botín rastreado:",
    lootRollingEnded = "Loot Rolling terminado.",
    reRollConfirmed = "Nueva tirada confirmada.",
    noEligibleReRolls = "No hay nuevas tiradas elegibles.",
    noItemRolling = "Actualmente no se está tirando por ningún objeto.",
    softResImported = "¡Soft-Reserve importadas!",
    softResOverwrite = "Los datos de soft-reserve ya existen. Importar nuevos datos los sobrescribirá. ¿Continuar?",
    csvParseError = "Error de análisis CSV:",
    lootWatcherDataDeleted = "Todos los datos del vigilante de botín han sido eliminados.",
    rollStartWithReserves = "Tirada para: %s - Reservado por: %s",
    rollStartNoReserves = "Tirada para: %s - Sin soft-reserve. /roll - MS, /roll 99 - OS",
    rollAnnounceLocalization = "Idioma de anuncio de tirada actual: %s",
    rollEndsSoon = "La tirada termina en %s",
    rollEndedWinner = "Tirada terminada. Ganador: %s con tirada - %d (especialización %s)",
    rollEndedNoRolls = "Tirada terminada. No se registraron tiradas.",
    itemIDError = "No se pudo obtener el ID del objeto o enlace.",
    notLootMaster = "No eres el maestro del botín.",
    notInRaid = "No estás en el grupo de banda.",
    lootNotMaster = "El botín maestro no está habilitado. Sistema de botín actual: %s",
    noCSVText = "¡No hay texto CSV para importar!",
    invalidCSVFormat = "Formato CSV no válido (faltan comas o fila de encabezado).",
    missingCSVColumn = "CSV falta la columna requerida: |cffffff00%s|r",
    softResDeleted = "Todas las soft-reserve han sido eliminadas.",
    thresholdChanged = "Umbral de análisis del vigilante de botín cambiado a: %s",
    itemIsBeingRolledFor = "La sesión de tirada para %s aún no ha terminado.",
    rollingCancelled = "La sesión de tirada para %s ha sido cancelada.",
  },
  dialogs = {
    confirmEndRoll = "¿Estás seguro de que quieres terminar la tirada?",
    confirmReRoll = "¿Estás seguro de que quieres volver a tirar por este objeto?",
    confirmCancelRoll = "¿Estás seguro de que quieres cancelar la sesión de tirada?",
    confirmOverwrite = "Los datos de soft-reserve ya existen. Importar nuevos datos los sobrescribirá. ¿Continuar?",
    confirmDeleteWatcher = "¿Estás seguro de que quieres eliminar TODOS los datos del vigilante de botín? Esto no se puede deshacer.",
    confirmDeleteSoftRes = "¿Estás seguro de que quieres eliminar TODOS los datos de soft-reserve? Esto no se puede deshacer.",
    yes = "Sí",
    no = "No",
  },
  regex = {
    playerLoot = "^(.+) recibe botín: (.+)%.$",
    selfLoot = "^Recibes botín: (.+)%.$",
    goldShare = "Tu parte del botín es",
    gold = "(%d+)%s*Oro",
    silver = "(%d+)%s*Plata",
    copper = "(%d+)%s*Cobre",
    systemRoll = "^(%S+) saca (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Buscar reservas...",
    searchLoot = "Buscar botín...",
  },
}

-- Russian (ruRU)
localeBasedMessages["ruRU"] = {
  system = {
    addonLoaded = "Аддон загружен",
    moduleEnabled = "Модуль распределения добычи включен.",
    moduleDisabled = "Модуль распределения добычи отключен.",
    joinedRaid = "Наблюдатель добычи активирован, порог анализа:",
    leftRaid = "Наблюдатель добычи деактивирован.",
    trackedLoot = "Отслеживаемая добыча:",
    lootRollingEnded = "Распределение добычи завершено.",
    reRollConfirmed = "Перебросок подтвержден.",
    noEligibleReRolls = "Нет доступных перебросков.",
    noItemRolling = "В данный момент не разыгрывается ни одного предмета.",
    softResImported = "Soft-Reserve импортированы!",
    softResOverwrite = "Данные soft-reserve уже существуют. Импорт новых данных перепишет их. Продолжить?",
    csvParseError = "Ошибка анализа CSV:",
    lootWatcherDataDeleted = "Все данные наблюдателя добычи были удалены.",
    rollStartWithReserves = "Бросок для: %s - Зарезервировано: %s",
    rollStartNoReserves = "Бросок для: %s - Без soft-reserve. /roll - ОС, /roll 99 - ВС",
    rollAnnounceLocalization = "Текущая локализация объявления броска: %s",
    rollEndsSoon = "Бросок заканчивается через %s",
    rollEndedWinner = "Бросок завершен. Победитель: %s с броском - %d (специализация %s)",
    rollEndedNoRolls = "Бросок завершен. Броски не зарегистрированы.",
    itemIDError = "Не удалось получить ID предмета или ссылку.",
    notLootMaster = "Вы не являетесь мастером добычи.",
    notInRaid = "Вы не в рейдовой группе.",
    lootNotMaster = "Мастер добычи не включен. Текущая система добычи: %s",
    noCSVText = "Нет CSV текста для импорта!",
    invalidCSVFormat = "Неверный формат CSV (отсутствуют запятые или строка заголовка).",
    missingCSVColumn = "В CSV отсутствует обязательная колонка: |cffffff00%s|r",
    softResDeleted = "Все soft-reserve были удалены.",
    thresholdChanged = "Порог анализа наблюдателя добычи изменен на: %s",
    itemIsBeingRolledFor = "Сессия броска для %s еще не закончилась.",
    rollingCancelled = "Сессия броска для %s была отменена.",
  },
  dialogs = {
    confirmEndRoll = "Вы уверены, что хотите завершить бросок?",
    confirmReRoll = "Вы уверены, что хотите перебросить этот предмет?",
    confirmCancelRoll = "Вы уверены, что хотите отменить сессию броска?",
    confirmOverwrite = "Данные soft-reserve уже существуют. Импорт новых данных перепишет их. Продолжить?",
    confirmDeleteWatcher = "Вы уверены, что хотите удалить ВСЕ данные наблюдателя добычи? Это нельзя отменить.",
    confirmDeleteSoftRes = "Вы уверены, что хотите удалить ВСЕ данные soft-reserve? Это нельзя отменить.",
    yes = "Да",
    no = "Нет",
  },
  regex = {
    playerLoot = "^(.+) получает добычу: (.+)%.$",
    selfLoot = "^Ваша добыча: (.+)%.$",
    goldShare = "Ваша доля добычи:",
    gold = "(%d+)%s*золот",
    silver = "(%d+)%s*сереб",
    copper = "(%d+)%s*медн",
    systemRoll = "^(%S+) выбрасывает (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Поиск резервов...",
    searchLoot = "Поиск добычи...",
  },
}

-- Portuguese (Brazil)
localeBasedMessages["ptBR"] = {
  system = {
    addonLoaded = "Addon Carregado",
    moduleEnabled = "Módulo de loot roll habilitado.",
    moduleDisabled = "Módulo de loot roll desabilitado.",
    joinedRaid = "Você se juntou ao grupo de raide. Observador de Loot ativado, limite de análise:",
    leftRaid = "Você saiu do grupo de raide. Observador de Loot desativado.",
    trackedLoot = "Loot rastreado:",
    lootRollingEnded = "Loot Rolling terminado.",
    reRollConfirmed = "Re-roll confirmado.",
    noEligibleReRolls = "Nenhum re-roll elegível.",
    noItemRolling = "Nenhum item está sendo rolado atualmente.",
    softResImported = "Soft-Reserve importadas!",
    softResOverwrite = "Dados de soft-reserve já existem. Importar novos dados irá sobrescrever. Continuar?",
    csvParseError = "Erro de análise CSV:",
    lootWatcherDataDeleted = "Todos os dados do observador de loot foram deletados.",
    rollStartWithReserves = "Roll para: %s - Reservado por: %s",
    rollStartNoReserves = "Roll para: %s - Sem soft-reserve. /roll - MS, /roll 99 - OS",
    rollAnnounceLocalization = "Idioma atual do anúncio de roll: %s",
    rollEndsSoon = "Roll termina em %s",
    rollEndedWinner = "Roll terminado. Vencedor: %s com roll - %d (especialização %s)",
    rollEndedNoRolls = "Roll terminado. Nenhum roll registrado.",
    itemIDError = "Não foi possível obter ID do item ou link.",
    notLootMaster = "Você não é o mestre do loot.",
    notInRaid = "Você não está no grupo de raide.",
    lootNotMaster = "Loot master não está habilitado. Sistema de loot atual: %s",
    noCSVText = "Nenhum texto CSV para importar!",
    invalidCSVFormat = "Formato CSV inválido (vírgulas ausentes ou linha de cabeçalho).",
    missingCSVColumn = "CSV está faltando a coluna obrigatória: |cffffff00%s|r",
    softResDeleted = "Todas as soft-reserve foram deletadas.",
    thresholdChanged = "Limite de análise do observador de loot alterado para: %s",
    itemIsBeingRolledFor = "Sessão de roll para %s ainda não terminou.",
    rollingCancelled = "Sessão de roll para %s foi cancelada."
  },
  dialogs = {
    confirmEndRoll = "Tem certeza de que quer terminar o roll?",
    confirmReRoll = "Tem certeza de que quer fazer re-roll deste item?",
    confirmCancelRoll = "Tem certeza de que quer cancelar a sessão de roll?",
    confirmOverwrite = "Dados de soft-reserve já existem. Importar novos dados irá sobrescrever. Continuar?",
    confirmDeleteWatcher = "Tem certeza de que quer deletar TODOS os dados do observador de loot? Isso não pode ser desfeito.",
    confirmDeleteSoftRes = "Tem certeza de que quer deletar TODOS os dados de soft-reserve? Isso não pode ser desfeito.",
    yes = "Sim",
    no = "Não",
  },
  regex = {
    playerLoot = "^(.+) recebe loot: (.+)%.$",
    selfLoot = "^Você recebe loot: (.+)%.$",
    goldShare = "Sua parte do loot é",
    gold = "(%d+)%s*Ouro",
    silver = "(%d+)%s*Prata",
    copper = "(%d+)%s*Cobre",
    systemRoll = "^(%S+) rola (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Buscar reservas...",
    searchLoot = "Buscar loot...",
  },
}

-- Italian (Italy)
localeBasedMessages["itIT"] = {
  system = {
    addonLoaded = "Addon Caricato",
    moduleEnabled = "Modulo loot roll abilitato.",
    moduleDisabled = "Modulo loot roll disabilitato.",
    joinedRaid = "Ti sei unito al gruppo raid. Osservatore Loot attivato, soglia di analisi:",
    leftRaid = "Hai lasciato il gruppo raid. Osservatore Loot disattivato.",
    trackedLoot = "Loot tracciato:",
    lootRollingEnded = "Loot Rolling terminato.",
    reRollConfirmed = "Re-roll confermato.",
    noEligibleReRolls = "Nessun re-roll idoneo.",
    noItemRolling = "Nessun oggetto è attualmente in fase di roll.",
    softResImported = "Soft-Reserve importate!",
    softResOverwrite = "I dati di soft-reserve esistono già. L'importazione di nuovi dati li sovrascriverà. Continuare?",
    csvParseError = "Errore di analisi CSV:",
    lootWatcherDataDeleted = "Tutti i dati dell'osservatore loot sono stati eliminati.",
    rollStartWithReserves = "Roll per: %s - Riservato da: %s",
    rollStartNoReserves = "Roll per: %s - Nessuna soft-reserve. /roll - MS, /roll 99 - OS",
    rollAnnounceLocalization = "Lingua annuncio roll corrente: %s",
    rollEndsSoon = "Il roll termina in %s",
    rollEndedWinner = "Roll terminato. Vincitore: %s con roll - %d (specializzazione %s)",
    rollEndedNoRolls = "Roll terminato. Nessun roll registrato.",
    itemIDError = "Impossibile ottenere ID oggetto o collegamento.",
    notLootMaster = "Non sei il master del loot.",
    notInRaid = "Non sei nel gruppo raid.",
    lootNotMaster = "Master loot non è abilitato. Sistema loot attuale: %s",
    noCSVText = "Nessun testo CSV da importare!",
    invalidCSVFormat = "Formato CSV non valido (virgole mancanti o riga intestazione).",
    missingCSVColumn = "CSV manca la colonna richiesta: |cffffff00%s|r",
    softResDeleted = "Tutte le soft-reserve sono state eliminate.",
    thresholdChanged = "Soglia di analisi dell'osservatore loot cambiata a: %s",
    itemIsBeingRolledFor = "La sessione di roll per %s non è ancora terminata.",
    rollingCancelled = "La sessione di roll per %s è stata annullata."
  },
  dialogs = {
    confirmEndRoll = "Sei sicuro di voler terminare il roll?",
    confirmReRoll = "Sei sicuro di voler fare re-roll di questo oggetto?",
    confirmCancelRoll = "Sei sicuro di voler annullare la sessione di roll?",
    confirmOverwrite = "I dati di soft-reserve esistono già. L'importazione di nuovi dati li sovrascriverà. Continuare?",
    confirmDeleteWatcher = "Sei sicuro di voler eliminare TUTTI i dati dell'osservatore loot? Questo non può essere annullato.",
    confirmDeleteSoftRes = "Sei sicuro di voler eliminare TUTTI i dati delle soft-reserve? Questo non può essere annullato.",
    yes = "Sì",
    no = "No",
  },
  regex = {
    playerLoot = "^(.+) riceve bottino: (.+)%.$",
    selfLoot = "^Ricevi bottino: (.+)%.$",
    goldShare = "La tua parte del bottino è",
    gold = "(%d+)%s*Oro",
    silver = "(%d+)%s*Argento",
    copper = "(%d+)%s*Rame",
    systemRoll = "^(%S+) tira (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Cerca riserve...",
    searchLoot = "Cerca bottino...",
  },
}


currentLocale = GetLocale() or "enUS"
LDData.messages = localeBasedMessages[currentLocale]
LDData.localeMessages = localeBasedMessages