local LootDistr, LDData = ...

local localeBasedMessages = {}

localeBasedMessages["enUS"] = {
  system = {
    addonLoaded = "Addon Loaded",
    moduleEnabled = "Loot roll module enabled.",
    moduleDisabled = "Loot roll module disabled.",
    joinedRaid = "You have joined the raid group. Loot Watcher activated, parsing threshold:",
    leftRaid = "You have left the raid group. Loot Watcher deactivated.",
    trackedLoot = "Tracked loot:",
    lootRollingEnded = "Loot Rolling ended.",
    reRollConfirmed = "Re-roll confirmed.",
    noEligibleReRolls = "No eligible re-rolls.",
    noItemRolling = "No item is currently being rolled.",
    softResImported = "Imported soft reserves!",
    softResOverwrite = "Soft reserve data already exists. Importing new data will overwrite it. Continue?",
    csvParseError = "CSV parse error:",
    lootWatcherDataDeleted = "All loot watcher data has been deleted.",
    rollStartWithReserves = "Roll for: %s - Reserved by: %s",
    rollStartNoReserves = "Roll for: %s - No soft reserves",
    rollEndedWinner = "Rolling ended. Winner: %s with roll - %d",
    rollEndedNoRolls = "Rolling ended. No rolls recorded.",
    itemIDError = "Could not get itemID or link.",
    notLootMaster = "You are not the loot master.",
    notInRaid = "You are not in the raid group.",
    lootNotMaster = "Master loot is not enabled. Current loot system: %s",
    noCSVText = "No CSV text to import!",
    invalidCSVFormat = "Not a valid CSV format (missing commas or header row).",
    missingCSVColumn = "CSV is missing required column: |cffffff00%s|r",
    softResDeleted = "All soft reserves have been deleted.",
    thresholdChanged = "Loot Watcher parsing threshold changed to: %s",
    itemIsBeingRolledFor = "Rolling session for %s has not ended yet."
  },
  dialogs = {
    confirmEndRoll = "Are you sure you want to end rolling?",
    confirmReRoll = "Are you sure you want to re-roll this item?",
    confirmOverwrite = "Soft reserve data already exists. Importing new data will overwrite it. Continue?",
    confirmDeleteWatcher = "Are you sure you want to delete ALL loot watcher data? This cannot be undone.",
    confirmDeleteSoftRes = "Are you sure you want to delete ALL soft reserves data? This cannot be undone.",
    yes = "Yes",
    no = "No",
  },
  regex = {
    playerLoot = "^(.+) receives loot: (.+)%.$",        -- LOOT_ITEM
    selfLoot = "^You receive loot: (.+)%.$",           -- LOOT_ITEM_SELF
    goldShare = "Your share of the loot is",           -- LOOT_MONEY_SPLIT
    gold = "(%d+)%s*Gold",
    silver = "(%d+)%s*Silver",
    copper = "(%d+)%s*Copper",
    systemRoll = "^(%S+) rolls (%d+) %((%d+)%-(%d+)%)$",-- system roll
  },
  ui = {
    searchReserves = "Search reserves...",
    searchLoot = "Search loot...",
  },
}

localeBasedMessages["deDE"] = {
  system = {
    addonLoaded = "Addon geladen",
    moduleEnabled = "Würfel-Modul aktiviert.",
    moduleDisabled = "Würfel-Modul deaktiviert.",
    joinedRaid = "Du bist der Schlachtgruppe beigetreten. Loot-Watcher aktiviert, Schwelle:",
    leftRaid = "Du hast die Schlachtgruppe verlassen. Loot-Watcher deaktiviert.",
    trackedLoot = "Verfolgte Beute:",
    lootRollingEnded = "Würfeln beendet.",
    reRollConfirmed = "Neuwurf bestätigt.",
    noEligibleReRolls = "Keine gültigen Neuwürfe.",
    noItemRolling = "Kein aktueller Wurfgegenstand.",
    softResImported = "Reservierungen importiert!",
    softResOverwrite = "Reservierungsdaten vorhanden. Importieren wird sie überschreiben. Fortfahren?",
    csvParseError = "CSV-Analysefehler:",
    lootWatcherDataDeleted = "Alle Loot-Watcher-Daten gelöscht.",
    rollStartWithReserves = "Würfeln für: %s - Reserviert von: %s",
    rollStartNoReserves = "Würfeln für: %s - Keine Reservierung",
    rollEndedWinner = "Würfeln beendet. Gewinner: %s mit Wurf - %d",
    rollEndedNoRolls = "Würfeln beendet. Keine Würfe aufgezeichnet.",
    itemIDError = "Could not get itemID or link.",     -- untranslated
    notLootMaster = "Du bist nicht der Plündermeister.",
    notInRaid = "Du bist nicht in einer Schlachtgruppe.",
    lootNotMaster = "Plündermeister ist nicht aktiviert. Aktuelles System: %s",
    noCSVText = "Kein CSV‑Text zum Importieren!",
    invalidCSVFormat = "Ungültiges CSV-Format (fehlende Kommata oder Kopfzeile).",
    missingCSVColumn = "CSV fehlt erforderliche Spalte: |cffffff00%s|r",
    softResDeleted = "Alle Reservierungen wurden gelöscht.",
    thresholdChanged = "Loot-Schwelle geändert zu: %s",
  },
  dialogs = {
    confirmEndRoll = "Bist du sicher, dass du das Würfeln beenden willst?",
    confirmReRoll = "Bist du sicher, dass du für dieses Item neu würfeln willst?",
    confirmOverwrite = "Reservierungsdaten vorhanden. Importieren wird sie überschreiben. Fortfahren?",
    confirmDeleteWatcher = "Bist du sicher, dass du ALLE Loot-Watcher-Daten löschen willst? Das ist irreversibel.",
    confirmDeleteSoftRes = "Bist du sicher, dass du ALLE Soft-Res-Daten löschen willst? Das ist irreversibel.",
    yes = "Ja",
    no = "Nein",
  },
  regex = {
    playerLoot = "^(.+) erhält Beute: (.+)%.$",
    selfLoot = "^Ihr erhaltet Beute: (.+)%.$",
    goldShare = "Euer Anteil an der Beute ist",
    gold = "(%d+)%s*Gold",
    silver = "(%d+)%s*Silber",
    copper = "(%d+)%s*Kupfer",
    systemRoll = "^(%S+) würfelt (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Reservierungen durchsuchen...",
    searchLoot = "Beute durchsuchen...",
  },
}

localeBasedMessages["frFR"] = {
  system = {
    addonLoaded = "Add‑on chargé",
    moduleEnabled = "Module de lancé de dés activé.",
    moduleDisabled = "Module de lancé de dés désactivé.",
    joinedRaid = "Vous avez rejoint le raid. Loot‑Watcher activé, seuil :",
    leftRaid = "Vous avez quitté le raid. Loot‑Watcher désactivé.",
    trackedLoot = "Butin suivi :",
    lootRollingEnded = "Jet terminé.",
    reRollConfirmed = "Relance confirmée.",
    noEligibleReRolls = "Aucune relance possible.",
    noItemRolling = "Aucun objet en cours de jet.",
    softResImported = "Réserves importées !",
    softResOverwrite = "Données existantes. Importation écrasera l’ancienne. Continuer ?",
    csvParseError = "Erreur d’analyse CSV :",
    lootWatcherDataDeleted = "Toutes les données de Loot‑Watcher ont été supprimées.",
    rollStartWithReserves = "Lancer pour : %s – Réservé par : %s",
    rollStartNoReserves = "Lancer pour : %s – Pas de réserves",
    rollEndedWinner = "Jet terminé. Gagnant : %s avec %d",
    rollEndedNoRolls = "Jet terminé. Aucun jet enregistré.",
    itemIDError = "Impossible d’obtenir l’ID ou le lien de l’objet.",
    notLootMaster = "Vous n’êtes pas le maître du butin.",
    notInRaid = "Vous n’êtes pas dans un raid.",
    lootNotMaster = "Butin maître non activé. Système actuel : %s",
    noCSVText = "Aucun texte CSV à importer !",
    invalidCSVFormat = "Format CSV invalide (virgules ou entête manquant).",
    missingCSVColumn = "Colonne manquante : |cffffff00%s|r",
    softResDeleted = "Toutes les réserves ont été supprimées.",
    thresholdChanged = "Seuil modifié à : %s",
  },
  dialogs = {
    confirmEndRoll = "Voulez‑vous vraiment terminer le jet ?",
    confirmReRoll = "Voulez‑vous vraiment relancer cet objet ?",
    confirmOverwrite = "Données existantes. Continuer l’écrasement ?",
    confirmDeleteWatcher = "Supprimer TOUTES les données Loot‑Watcher ? Cette action est irréversible.",
    confirmDeleteSoftRes = "Supprimer TOUTES les données soft‑res ? Irretrievable.",
    yes = "Oui",
    no = "Non",
  },
  regex = {
    playerLoot = "^(.+) reçoit le butin : (.+)%.$",
    selfLoot = "^Vous recevez le butin : (.+)%.$",
    goldShare = "Votre part du butin est",
    gold = "(%d+)%s*Or",
    silver = "(%d+)%s*Argent",
    copper = "(%d+)%s*Cuivre",
    systemRoll = "^(%S+) obtient un (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Rechercher les réserves...",
    searchLoot = "Rechercher le butin...",
  },
}

localeBasedMessages["ruRU"] = {
  system = {
    addonLoaded = "Аддон загружен",
    moduleEnabled = "Модуль бросков активирован.",
    moduleDisabled = "Модуль бросков деактивирован.",
    joinedRaid = "Вы присоединились к рейду. Loot‑Watcher активирован, порог:",
    leftRaid = "Вы вышли из рейда. Loot‑Watcher деактивирован.",
    trackedLoot = "Отслеживаемое добыча:",
    lootRollingEnded = "Броски завершены.",
    reRollConfirmed = "Пере‑бросок подтвержден.",
    noEligibleReRolls = "Нет подходящих пере‑бросков.",
    noItemRolling = "Нет предметов для броска.",
    softResImported = "Резервы импортированы!",
    softResOverwrite = "Есть резервы. Импорт перепишет. Продолжить?",
    csvParseError = "Ошибка CSV:",
    lootWatcherDataDeleted = "Данные Loot‑Watcher удалены.",
    rollStartWithReserves = "Ролл на: %s – зарезервировано: %s",
    rollStartNoReserves = "Ролл на: %s – без резервов",
    rollEndedWinner = "Роллы окончены. Победитель: %s с %d",
    rollEndedNoRolls = "Роллы окончены. Нет бросков.",
    itemIDError = "Не удалось получить ID или ссылку предмета.",
    notLootMaster = "Вы не мастер добычи.",
    notInRaid = "Вы не в рейде.",
    lootNotMaster = "Мастер‑добыча отключена. Текущий: %s",
    noCSVText = "Нет текста CSV для импорта!",
    invalidCSVFormat = "Неверный формат CSV.",
    missingCSVColumn = "В CSV отсутствует столбец: |cffffff00%s|r",
    softResDeleted = "Все резервы удалены.",
    thresholdChanged = "Порог изменён: %s",
  },
  dialogs = {
    confirmEndRoll = "Вы уверены, что хотите завершить броски?",
    confirmReRoll = "Перебросить этот предмет?",
    confirmOverwrite = "Есть резервы. Продолжить и перезаписать?",
    confirmDeleteWatcher = "Удалить ВСЕ данные Loot‑Watcher? Это необратимо.",
    confirmDeleteSoftRes = "Удалить ВСЕ данные soft‑res? Это необратимо.",
    yes = "Да",
    no = "Нет",
  },
  regex = {
    playerLoot = "^(.+) получает добычу: (.+)%.$",
    selfLoot = "^Вы получаете добычу: (.+)%.$",
    goldShare = "Ваша доля добычи",
    gold = "(%d+)%s*золота",
    silver = "(%d+)%s*серебра",
    copper = "(%d+)%s*меди",
    systemRoll = "^(%S+) бросает кости: (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Поиск резервов...",
    searchLoot = "Поиск добычи...",
  },
}

localeBasedMessages["esES"] = {
  system = {
    addonLoaded = "Addon cargado",
    moduleEnabled = "Módulo de tirada activado.",
    moduleDisabled = "Módulo de tirada desactivado.",
    joinedRaid = "Te uniste al grupo. Loot‑Watcher activado, umbral:",
    leftRaid = "Saliste de la banda. Loot‑Watcher desactivado.",
    trackedLoot = "Botín rastreado:",
    lootRollingEnded = "Tirada finalizada.",
    reRollConfirmed = "Re‑tirada confirmada.",
    noEligibleReRolls = "No hay re‑tiradas elegibles.",
    noItemRolling = "No hay objeto para tirada.",
    softResImported = "Reservas importadas!",
    softResOverwrite = "Reservas existen. ¿Sobrescribir?",
    csvParseError = "Error de CSV:",
    lootWatcherDataDeleted = "Datos de Loot‑Watcher eliminados.",
    rollStartWithReserves = "Tirada por: %s – Reservado por: %s",
    rollStartNoReserves = "Tirada por: %s – Sin reservas",
    rollEndedWinner = "Tirada finalizada. Ganador: %s con %d",
    rollEndedNoRolls = "Tirada finalizada. No se registraron tiradas.",
    itemIDError = "No se pudo obtener el ID o enlace.",
    notLootMaster = "No eres maestro de botín.",
    notInRaid = "No estás en la banda.",
    lootNotMaster = "Botín maestro no habilitado. Sistema: %s",
    noCSVText = "¡No hay texto CSV!",
    invalidCSVFormat = "Formato CSV inválido.",
    missingCSVColumn = "Falta columna en CSV: |cffffff00%s|r",
    softResDeleted = "Reservas eliminadas.",
    thresholdChanged = "Umbral cambiado a: %s",
  },
  dialogs = {
    confirmEndRoll = "¿Seguro que quieres terminar la tirada?",
    confirmReRoll = "¿Seguro que quieres re‑tirar este objeto?",
    confirmOverwrite = "Reservas existen. ¿Sobrescribir?",
    confirmDeleteWatcher = "Eliminar TODOS los datos de Loot‑Watcher? Irreversible.",
    confirmDeleteSoftRes = "Eliminar TODOS los datos soft‑res? Irreversible.",
    yes = "Sí",
    no = "No",
  },
  regex = {
    playerLoot = "^(.+) recibe botín: (.+)%.$",
    selfLoot = "^Recibes botín: (.+)%.$",
    goldShare = "Tu parte del botín es",
    gold = "(%d+)%s*oro",
    silver = "(%d+)%s*plata",
    copper = "(%d+)%s*cobre",
    systemRoll = "^(%S+) tira los dados y obtiene (%d+) %((%d+)%-(%d+)%)$",
  },
  ui = {
    searchReserves = "Buscar reservas...",
    searchLoot = "Buscar botín...",
  },
}


currentLocale = GetLocale() or "enUS"
LDData.messages = localeBasedMessages[currentLocale]